# Generated by Django 6.1 on 2026-08-15 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0007_licensetypemaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('customer_code', models.CharField(db_column='Customer_Code', max_length=50, unique=True)),
                ('customer_name', models.CharField(db_column='Customer_Name', max_length=500)),
                ('company_name', models.CharField(blank=True, db_column='Company_Name', max_length=250, null=True)),
                ('email_id', models.EmailField(blank=True, db_column='Email_Id', max_length=254, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('pincode', models.CharField(blank=True, db_column='Pincode', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, db_column='GST_Number', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer_rating', models.ForeignKey(blank=True, db_column='Customer_Rating_Id', null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.ratingtypemaster')),
                ('customer_type', models.ForeignKey(blank=True, db_column='Customer_Type_Id', null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.customertypemaster')),
            ],
            options={
                'db_table': 'CustomerDetails_tbl',
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('contact_name', models.CharField(db_column='Contact_Name', max_length=250)),
                ('contact_number', models.CharField(db_column='Contact_Number', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='Customer_Id', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Customers.customerdetails')),
            ],
            options={
                'db_table': 'CustomerContact_tbl',
            },
        ),
        migrations.CreateModel(
            name='CustomerLicenseDetails',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tally_serial_number', models.CharField(blank=True, db_column='Tally_Serial_Number', max_length=100, null=True)),
                ('admin_id', models.CharField(blank=True, db_column='AdminId', max_length=250, null=True)),
                ('expiry_date', models.DateField(blank=True, db_column='Expiry_Date', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('created_by', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='Customer_Id', on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='Customers.customerdetails')),
                ('license_type', models.ForeignKey(blank=True, db_column='License_Type_Id', null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.licensetypemaster')),
            ],
            options={
                'db_table': 'CustomerLicenseDetails_tbl',
            },
        ),
    ]
