# Generated by Django 6.1 on 2026-08-13 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeMaster',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('product_type_name', models.CharField(db_column='Product_Type_Name', max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('created_by', models.ForeignKey(db_column='Created_By', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProductTypeMaster_tbl',
            },
        ),
    ]
