# Generated by Django 6.1 on 2026-08-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttypemaster',
            name='product_type_name',
            field=models.CharField(db_column='Product_Type_Name', max_length=255),
        ),
    ]
