# Generated by Django 6.1 on 2026-08-14 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_producttypemaster_product_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTypeMaster',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('customer_type_name', models.CharField(db_column='Customer_Type_Name', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('created_by', models.ForeignKey(db_column='Created_By', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CustomerTypeMaster_tbl',
            },
        ),
    ]
