# Generated by Django 6.1 on 2026-08-25 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_licensetypemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Menu_Name', models.CharField(db_column='Menu_Name', max_length=100)),
                ('Icon', models.CharField(blank=True, db_column='Icon', max_length=50, null=True)),
                ('Display_Order', models.IntegerField(db_column='Display_Order', default=0)),
                ('Is_Active', models.BooleanField(db_column='Is_Active', default=True)),
                ('Parent_Id', models.ForeignKey(blank=True, db_column='Parent_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubMenus', to='masters.menumaster')),
            ],
            options={
                'db_table': 'MenuMaster_tbl',
                'ordering': ['Display_Order', 'Id'],
            },
        ),
    ]
