# Generated by Django 6.1 on 2026-08-25 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0008_menumaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Staff_Image', models.ImageField(blank=True, db_column='Staff_Image', null=True, upload_to='staff/')),
                ('Full_Name', models.CharField(db_column='Full_Name', max_length=200)),
                ('Designation', models.CharField(db_column='Designation', max_length=150)),
                ('Email_Address', models.EmailField(db_column='Email_Address', max_length=255)),
                ('Phone_Number', models.CharField(db_column='Phone_Number', max_length=20)),
                ('Hire_Date', models.DateField(db_column='Hire_Date')),
                ('Role', models.CharField(db_column='Role', max_length=100)),
                ('Is_Active', models.BooleanField(db_column='Is_Active', default=True)),
                ('Created_On', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('Created_By', models.ForeignKey(blank=True, db_column='Created_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_created_by', to=settings.AUTH_USER_MODEL)),
                ('User_Id', models.OneToOneField(db_column='User_Id', on_delete=django.db.models.deletion.CASCADE, related_name='staff_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'StaffDetails_tbl',
            },
        ),
        migrations.CreateModel(
            name='StaffMenuPermission',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Can_View', models.BooleanField(db_column='Can_View', default=True)),
                ('Menu', models.ForeignKey(db_column='Menu_Id', on_delete=django.db.models.deletion.CASCADE, related_name='StaffPermissions', to='masters.menumaster')),
                ('Staff', models.ForeignKey(db_column='Staff_Id', on_delete=django.db.models.deletion.CASCADE, related_name='MenuPermissions', to='staff.staffdetails')),
            ],
            options={
                'db_table': 'StaffMenuPermission_tbl',
                'constraints': [models.UniqueConstraint(fields=('Staff', 'Menu'), name='unique_staff_menu_permission')],
            },
        ),
    ]
