# Generated by Django 6.1 on 2026-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmenupermission',
            name='Can_Add',
            field=models.BooleanField(db_column='Can_Add', default=False),
        ),
        migrations.AddField(
            model_name='staffmenupermission',
            name='Can_Delete',
            field=models.BooleanField(db_column='Can_Delete', default=False),
        ),
        migrations.AddField(
            model_name='staffmenupermission',
            name='Can_Edit',
            field=models.BooleanField(db_column='Can_Edit', default=False),
        ),
    ]
