# Generated by Django 6.1 on 2026-09-01 23:18

import django.db.models.deletion
import staff.document_files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffmenupermission_can_add_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Document_File', models.FileField(db_column='Document_File', upload_to=staff.document_files.staff_document_upload_to, validators=[staff.document_files.validate_staff_document])),
                ('Original_Name', models.CharField(db_column='Original_Name', max_length=255)),
                ('Mime_Type', models.CharField(db_column='Mime_Type', max_length=150)),
                ('File_Size', models.PositiveBigIntegerField(db_column='File_Size')),
                ('Uploaded_On', models.DateTimeField(auto_now_add=True, db_column='Uploaded_On')),
                ('Staff_Id', models.ForeignKey(db_column='Staff_Id', on_delete=django.db.models.deletion.CASCADE, related_name='Documents', to='staff.staffdetails')),
                ('Uploaded_By', models.ForeignKey(blank=True, db_column='Uploaded_By', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'StaffDocument_tbl',
                'ordering': ['-Uploaded_On', '-Id'],
            },
        ),
    ]
