# Generated by Django 6.1 on 2026-08-16 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        ('masters', '0007_licensetypemaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryDetails_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shedule_Date', models.DateField(db_column='Shedule_Date')),
                ('Resource_Id', models.IntegerField(blank=True, db_column='Resource_Id', null=True)),
                ('Created_On', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('Created_Id', models.ForeignKey(db_column='Created_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Customer_Id', models.ForeignKey(db_column='Customer_Id', on_delete=django.db.models.deletion.CASCADE, to='Customers.customerdetails')),
                ('Source_Id', models.ForeignKey(db_column='Source_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.sourcetypemaster')),
                ('Status_Id', models.ForeignKey(db_column='Status_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.statustypemaster')),
            ],
            options={
                'db_table': 'InquiryDetails_tbl',
            },
        ),
        migrations.CreateModel(
            name='InquiryProductDetails_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(db_column='Quantity', decimal_places=2, max_digits=10)),
                ('Rate', models.DecimalField(db_column='Rate', decimal_places=2, max_digits=10)),
                ('Amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=12)),
                ('Requirment', models.TextField(blank=True, db_column='Requirment', null=True)),
                ('Created_On', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('Created_By', models.ForeignKey(db_column='Created_By', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Inquiry_Id', models.ForeignKey(db_column='Inquiry_Id', on_delete=django.db.models.deletion.CASCADE, to='Inquiry.inquirydetails_tbl')),
                ('ProductType_Id', models.ForeignKey(db_column='ProductType_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.producttypemaster')),
            ],
            options={
                'db_table': 'InquiryProductDetails_tbl',
            },
        ),
    ]
