# Generated by Django 6.1 on 2026-08-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inquiry', '0001_initial'),
        ('staff', '0002_staffmenupermission_can_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirydetails_tbl',
            name='Resource_Id',
            field=models.ForeignKey(blank=True, db_column='Resource_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to='staff.staffdetails'),
        ),
    ]
