# Generated by Django 6.1 on 2026-08-27 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inquiry', '0002_alter_inquirydetails_tbl_resource_id'),
        ('staff', '0002_staffmenupermission_can_add_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_Date', models.DateField(db_column='Work_Date')),
                ('Start_Time', models.DateTimeField(db_column='Start_Time')),
                ('End_Time', models.DateTimeField(blank=True, db_column='End_Time', null=True)),
                ('Progress_Notes', models.TextField(blank=True, db_column='Progress_Notes')),
                ('Task_Status', models.CharField(choices=[('active', 'Active'), ('progress_saved', 'Progress Saved'), ('payment_pending', 'Payment Pending')], db_column='Task_Status', default='active', max_length=20)),
                ('Created_On', models.DateTimeField(auto_now_add=True, db_column='Created_On')),
                ('Updated_On', models.DateTimeField(auto_now=True, db_column='Updated_On')),
                ('Created_By', models.ForeignKey(db_column='Created_By', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('Inquiry_Id', models.ForeignKey(db_column='Inquiry_Id', on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='Inquiry.inquirydetails_tbl')),
                ('Resource_Id', models.ForeignKey(db_column='Resource_Id', on_delete=django.db.models.deletion.PROTECT, related_name='task_progress', to='staff.staffdetails')),
            ],
            options={
                'db_table': 'InquiryTaskProgress_tbl',
                'ordering': ['-Start_Time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('End_Time__isnull', True)), fields=('Resource_Id',), name='unique_active_task_per_resource')],
            },
        ),
    ]
