# Generated by Django 6.1 on 2026-09-18 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inquiry', '0019_productbillingfollowup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='Product_Billing',
            field=models.ForeignKey(blank=True, db_column='Product_Billing_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='Inquiry.productbilling'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='Inquiry_Product',
            field=models.ForeignKey(blank=True, db_column='Inquiry_Product_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='Inquiry.inquiryproductdetails_tbl'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='Payment_Date',
            field=models.DateTimeField(auto_now_add=True, db_column='Payment_Date', null=True),
        ),
        migrations.AddConstraint(
            model_name='paymentdetail',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('Inquiry_Product__isnull', False), ('Product_Billing__isnull', True)), models.Q(('Inquiry_Product__isnull', True), ('Product_Billing__isnull', False)), _connector='OR'), name='payment_detail_exactly_one_source'),
        ),
    ]
